apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: podinfo-secrets
  namespace: default
spec:
  encryptedData:
    # Fake encrypted string for CV demonstration
    API_KEY: AgBfXb3qJ9sXlY0abc123fakejunkdataherexyz8jF9z
