apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 1. Master list of all files to apply
resources:
  - deployment.yaml
  - service.yaml
  - tetragon-policy.yaml
  - gateway.yaml
  - httproute.yaml
#  - sealed-secret.yaml

# 2. Inject these labels into EVERY file automatically
commonLabels:
  managed-by: argocd

